name: Release

on:
    push:
        branches: '**'

jobs:
    release:
        runs-on: windows-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - run: npm i
            - run: npm run pkg
            - run: echo "VERSION=$(date +'%Y.%m.%d.his')" >> $GITHUB_ENV
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ./VRChatOSCAlerts.exe
                  asset_name: VRChatOSCAlerts_v${{ env.NOW }}.exe
                  release_name: Release v${{ env.NOW }}
                  tag: v${{ env.NOW }}
                  overwrite: true
                  body: "test text"